### ISSUE TITLE
Cool Shows

### ISSUE THREAD

**Issue by fionachuancai** [JavaScriptAcademy/CoolShows#1]
- The project consist of three parts:
- [x] Build Working Environment #2
- [x] Creating and Running Meteor Project on Linux OS #3 
- [x] Login module #5 
- [x] Ticket Booking module  #6 
- [ ] Adding Comments module
- Other works to do
- [ ] Define policies 
- [ ] Data models
